on:
  push
#    branches:
#      - master

name: Full build
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 13.x
        uses: actions/setup-node@v1
        with:
          node-version: 13.x
      - name: clean install
        run: make clean
      - name: lys-test
        run: make lys-test
      - name: lys-build
        run: make lys-build
      - name: test golden files
        run: make only-test